version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: elearning-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - elearning-network

  frontend:
    build:
      context: ./frontend
    container_name: elearning-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    networks:
      - elearning-network

networks:
  elearning-network:
    driver: bridge